spring:
  #数据源配置
  datasource:
    username: nasa
    password: 123456
    url: jdbc:h2:~/test1 #数据库默认在当前用户目录下，数据库不存在时会自动新建
    driver-class-name: org.h2.Driver

  #JPA配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #设置前台传入的日期格式
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  elasticsearch:
    #    elasticsearch 客户端 jest 配置
    jest:
      uris: http://localhost:9200  #要使用的 Elasticsearch 实例的逗号分隔列表，默认为 http://localhost:9200
      read-timeout: 60s   #读取超时实际，默认为 3s
      connection-timeout: 30s   #连接超时时间，默认为 3s

  data:
    elasticsearch:
      cluster-name: elasticsearch   #集群节点的名称、默认为 elasticsearch
      #以逗号分隔的集群节点地址列表，因为 spring-data-elasticsearch 使用 tcp 与 es 交互，所以是 9300 端口，而不是 http 方式的 9200
      cluster-nodes: localhost:9300

server:
  port: 8080    #修改服务器 http 端口，默认为 8080
  servlet:
    #    context-path: /h2Smil   #设置应用上下文，必须以"/"开头
    session:
      timeout: 60m #会话超时时间，如果未指定单位，则默认为秒。默认为 30m 即 30 分钟。
      cookie:
        name: h2smilCookie #会话 cookie 名称。
  tomcat:
    max-connections: 800  #服务器在任何给定时间接受和处理的最大连接数。默认为 1000
    max-threads: 300      #最大工作线程数。默认 200
    min-spare-threads: 30 #最小工作线程数。默认 10
    max-http-post-size: 4MB  # HTTP post 请求内容的最大大小。默认为 2MB
    uri-encoding: UTF-8 #用于解码URI的字符编码, 默认 UTF-8
  max-http-header-size: 50MB  #HTTP消息头的最大大小（字节）,单位 KB、MB、GB、TB
  connection-timeout: 60000 #


jasypt:
  encryptor:
    password: wangmaox  #加密的密钥，自定义即可，必填项
    algorithm: PBEWithMD5AndDES  #指定解密算法
    string-output-type: hexadecimal #设置加密内容输出的编码形式，可用的编码类型有 base64、hexadecimal（16进制）

author:
  infos:
    address: 长沙市天心区
    # Jasypt加密，格式为ENC(加密结果)
    email: 114
